version: '3.1'

#Set up PostgreSQL 10.x first
services:

  db:
    image: postgres:10-alpine
    #name: postgres 
    restart: always
    environment:
      - POSTGRES_PASSWORD=yourpassword
    networks:
      - cmdbuild 

  cmdbuild:
    image: trepz/cmdbuild:3.1.1
    #name: cmdbuild
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cmdbuild
      - DB_TYPE=ready2use_demo
      - CMDBUILD_USERNAME=cmdbuild
      - CMDBUILD_PASSWORD=cmdbuild
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - "8080:8080"
    networks:
      - cmdbuild

networks:
  cmdbuild: