version: '2.1'

#Set up PostgreSQL 10.x first
services:

  postgres:
    # This image is used because of the native PostGIS module installation
    image: mdillon/postgis:9.5-alpine    
    restart: always
    environment:
      - POSTGRES_PASSWORD=yourpassword
    networks:
      - cmdbuild 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cmdbuild:
    image: trepz/cmdbuild:3.1.1    
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cmdbuild
      - DB_TYPE=ready2use_demo
      - CMDBUILD_USERNAME=cmdbuild
      - CMDBUILD_PASSWORD=cmdbuild
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - "8080:8080"
    networks:
      - cmdbuild
    depends_on:
      postgres:
        condition: service_healthy

networks:
  cmdbuild: